### PR TITLE
Ship incoming log event metrics and remove plumbum 

### PR DESCRIPTION
**Pull request by idavidmcdonald**
https://trello.com/c/tZghClQt/354-add-a-hosted-graphite-alert-for-missing-logs
https://trello.com/c/8sezKAoU/365-remove-dependancy-of-plubum-from-cloudwatch-to-graphite-metric-exporter

See commit messages for further details.

### CODE REVIEW

**Review by Wynndow — COMMENTED** [review]
What was plumbum doing for us? It seems weird that we can just throw it out the window. What was it connecting to AWS for?

**Comment by CrystalPea** [comment]
@Wynndow I think it was allowing us to use Jinja as per below ticket, but we wrote a script that does it instead of plumbum:
https://trello.com/c/8sezKAoU/365-remove-dependancy-of-plubum-from-cloudwatch-to-graphite-metric-exporter

**Comment by Wynndow** [comment]
Yep totally, just wondering what plumbum was actually doing? It looks like it was using Jinja to populate a template, but it was also talking to AWS for something. Wondering what that something was.

**Comment by idavidmcdonald** [comment]
So from what I understand, Plumbum comes as part of leadbutt which makes it easy to create your config file. It makes the assumption that someone using it is going to query AWS to find out say the IDs of 40 different EC2 instances and then ship metrics defined by those 40 EC2 instances that you just found. The assumption was you would also use Jinja as part of that using a template that would take data from AWS as parameters. We were originally using plumbum to just take advantage of the built in jinja pipeline and actually didn't need (or at least not anymore) the access to AWS, however the connection to AWS was mandatory as part of the plumbum flow. Does that answer your question?

**Review by Wynndow — APPROVED** [review]

**Pull request merged**
